const languages = [
  { value: "af", text: "afrikaans" },
  { value: "sq", text: "albanian" },
  { value: "am", text: "amharic" },
  { value: "ar", text: "arabic" },
  { value: "hy", text: "armenian" },
  { value: "az", text: "azerbaijani" },
  { value: "eu", text: "basque" },
  { value: "be", text: "belarusian" },
  { value: "bn", text: "bengali" },
  { value: "bs", text: "bosnian" },
  { value: "bg", text: "bulgarian" },
  { value: "ca", text: "catalan" },
  { value: "ceb", text: "cebuano" },
  { value: "ny", text: "chichewa" },
  { value: "zh-n", text: "chinese (simplified)" },
  { value: "zh-w", text: "chinese (traditional)" },
  { value: "co", text: "corsican" },
  { value: "hr", text: "croatian" },
  { value: "cs", text: "czech" },
  { value: "da", text: "danish" },
  { value: "nl", text: "dutch" },
  { value: "en", text: "english" },
  { value: "eo", text: "esperanto" },
  { value: "et", text: "estonian" },
  { value: "tl", text: "filipino" },
  { value: "fi", text: "finnish" },
  { value: "fr", text: "french" },
  { value: "fy", text: "frisian" },
  { value: "gl", text: "galician" },
  { value: "ka", text: "georgian" },
  { value: "de", text: "german" },
  { value: "el", text: "greek" },
  { value: "gu", text: "gujarati" },
  { value: "ht", text: "haitian creole" },
  { value: "ha", text: "hausa" },
  { value: "haw", text: "hawaiian" },
  { value: "iw", text: "hebrew" },
  { value: "he", text: "hebrew" },
  { value: "hi", text: "hindi" },
  { value: "hmn", text: "hmong" },
  { value: "hu", text: "hungarian" },
  { value: "is", text: "icelandic" },
  { value: "ig", text: "igbo" },
  { value: "id", text: "indonesian" },
  { value: "ga", text: "irish" },
  { value: "it", text: "italian" },
  { value: "ja", text: "japanese" },
  { value: "jw", text: "javanese" },
  { value: "kn", text: "kannada" },
  { value: "kk", text: "kazakh" },
  { value: "km", text: "khmer" },
  { value: "ko", text: "korean" },
  { value: "ku", text: "kurdish (kurmanji)" },
  { value: "ky", text: "kyrgyz" },
  { value: "lo", text: "lao" },
  { value: "la", text: "latin" },
  { value: "lv", text: "latvian" },
  { value: "lt", text: "lithuanian" },
  { value: "lb", text: "luxembourgish" },
  { value: "mk", text: "macedonian" },
  { value: "mg", text: "malagasy" },
  { value: "ms", text: "malay" },
  { value: "ml", text: "malayalam" },
  { value: "mt", text: "maltese" },
  { value: "mi", text: "maori" },
  { value: "mr", text: "marathi" },
  { value: "mn", text: "mongolian" },
  { value: "my", text: "myanmar (burmese)" },
  { value: "ne", text: "nepali" },
  { value: "no", text: "norwegian" },
  { value: "or", text: "odia" },
  { value: "ps", text: "pashto" },
  { value: "fa", text: "persian" },
  { value: "pl", text: "polish" },
  { value: "pt", text: "portuguese" },
  { value: "pa", text: "punjabi" },
  { value: "ro", text: "romanian" },
  { value: "ru", text: "russian" },
  { value: "sm", text: "samoan" },
  { value: "gd", text: "scots gaelic" },
  { value: "sr", text: "serbian" },
  { value: "st", text: "sesotho" },
  { value: "sn", text: "shona" },
  { value: "sd", text: "sindhi" },
  { value: "si", text: "sinhala" },
  { value: "sk", text: "slovak" },
  { value: "sl", text: "slovenian" },
  { value: "so", text: "somali" },
  { value: "es", text: "spanish" },
  { value: "su", text: "sundanese" },
  { value: "sw", text: "swahili" },
  { value: "sv", text: "swedish" },
  { value: "tg", text: "tajik" },
  { value: "ta", text: "tamil" },
  { value: "te", text: "telugu" },
  { value: "th", text: "thai" },
  { value: "tr", text: "turkish" },
  { value: "uk", text: "ukrainian" },
  { value: "ur", text: "urdu" },
  { value: "ug", text: "uyghur" },
  { value: "uz", text: "uzbek" },
  { value: "vi", text: "vietnamese" },
  { value: "cy", text: "welsh" },
  { value: "xh", text: "xhosa" },
  { value: "yi", text: "yiddish" },
  { value: "yo", text: "yoruba" },
  { value: "zu", text: "zulu" },
];

// const languages = [
//   { value: "af", text: "Afrikaans" },
//   { value: "sq", text: "Albanian" },
//   { value: "am", text: "Amharic" },
//   { value: "ar", text: "Arabic" },
//   { value: "hy", text: "Armenian" },
//   { value: "as", text: "Assamese" },
//   { value: "ay", text: "Aymara" },
//   { value: "az", text: "Azerbaijani" },
//   { value: "bm", text: "Bambara" },
//   { value: "eu", text: "Basque" },
//   { value: "be", text: "Belarusian" },
//   { value: "bn", text: "Bengali" },
//   { value: "bho", text: "Bhojpuri" },
//   { value: "bs", text: "Bosnian" },
//   { value: "bg", text: "Bulgarian" },
//   { value: "ca", text: "Catalan" },
//   { value: "ceb", text: "Cebuano" },
//   { value: "zh-CN", text: "Chinese (Simplified)" },
//   { value: "zh-TW", text: "Chinese (Traditional)" },
//   { value: "co", text: "Corsican" },
//   { value: "hr", text: "Croatian" },
//   { value: "cs", text: "Czech" },
//   { value: "da", text: "Danish" },
//   { value: "dv", text: "Dhivehi" },
//   { value: "doi", text: "Dogri" },
//   { value: "nl", text: "Dutch" },
//   { value: "en", text: "English" },
//   { value: "eo", text: "Esperanto" },
//   { value: "et", text: "Estonian" },
//   { value: "ee", text: "Ewe" },
//   { value: "fil", text: "Filipino (Tagalog)" },
//   { value: "fi", text: "Finnish" },
//   { value: "fr", text: "French" },
//   { value: "fy", text: "Frisian" },
//   { value: "gl", text: "Galician" },
//   { value: "ka", text: "Georgian" },
//   { value: "de", text: "German" },
//   { value: "el", text: "Greek" },
//   { value: "gn", text: "Guarani" },
//   { value: "gu", text: "Gujarati" },
//   { value: "ht", text: "Haitian Creole" },
//   { value: "ha", text: "Hausa" },
//   { value: "haw", text: "Hawaiian" },
//   { value: "he", text: "Hebrew" },
//   { value: "hi", text: "Hindi" },
//   { value: "hmn", text: "Hmong" },
//   { value: "hu", text: "Hungarian" },
//   { value: "is", text: "Icelandic" },
//   { value: "ig", text: "Igbo" },
//   { value: "ilo", text: "Ilocano" },
//   { value: "id", text: "Indonesian" },
//   { value: "ga", text: "Irish" },
//   { value: "iy", text: "Italian" },
//   { value: "ja", text: "Japanese" },
//   { value: "jv", text: "Javanese" },
//   { value: "kn", text: "Kannada" },
//   { value: "kk", text: "Kazakh" },
//   { value: "km", text: "Khmer" },
//   { value: "rw", text: "Kinyarwanda" },
//   { value: "gom", text: "Konkani" },
//   { value: "ko", text: "Korean" },
//   { value: "kri", text: "Krio" },
//   { value: "ku", text: "Kurdish" },
//   { value: "ckb", text: "Kurdish (Sorani)" },
//   { value: "ky", text: "Kyrgyz" },
//   { value: "lo", text: "Lao" },
//   { value: "la", text: "Latin" },
//   { value: "lv", text: "Latvian" },
//   { value: "ln", text: "Lingala" },
//   { value: "lt", text: "Lithuanian" },
//   { value: "lg", text: "Luganda" },
//   { value: "lb", text: "Luxembourgish" },
//   { value: "mk", text: "Macedonian" },
//   { value: "mai", text: "Maithili" },
//   { value: "mg", text: "Malagasy" },
//   { value: "ms", text: "Malay" },
//   { value: "ml", text: "Malayalam" },
//   { value: "mt", text: "Maltese" },
//   { value: "mi", text: "Maori" },
//   { value: "mr", text: "Marathi" },
//   { value: "mni", text: "Meiteilon (Manipuri)" },
//   { value: "lus", text: "Mizo" },
//   { value: "mn", text: "Mongolian" },
//   { value: "my", text: "Myanmar (Burmese)" },
//   { value: "ne", text: "Nepali" },
//   { value: "no", text: "Norwegian" },
//   { value: "ny", text: "Nyanja (Chichewa)" },
//   { value: "or", text: "Odia (Oriya)" },
//   { value: "om", text: "Oromo" },
//   { value: "ps", text: "Pashto" },
//   { value: "fa", text: "Persian" },
//   { value: "pl", text: "Polish" },
//   { value: "pt", text: "Portuguese" },
//   { value: "pa", text: "Punjabi" },
//   { value: "qu", text: "Quechua" },
//   { value: "ro", text: "Romanian" },
//   { value: "ru", text: "Russian" },
//   { value: "sm", text: "Samoan" },
//   { value: "sa", text: "Sanskrit" },
//   { value: "gd", text: "Scots Gaelic" },
//   { value: "nso", text: "Sepedi" },
//   { value: "sr", text: "Serbian" },
//   { value: "st", text: "Sesotho" },
//   { value: "sn", text: "Shona" },
//   { value: "sd", text: "Sindhi" },
//   { value: "si", text: "Sinhala (Sinhalese)" },
//   { value: "sk", text: "Slovak" },
//   { value: "sl", text: "Slovenian" },
//   { value: "so", text: "Somali" },
//   { value: "es", text: "Spanish" },
//   { value: "su", text: "Sundanese" },
//   { value: "sw", text: "Swahili" },
//   { value: "sv", text: "Swedish" },
//   { value: "tl", text: "Tagalog (Filipino)" },
//   { value: "tg", text: "Tajik" },
//   { value: "ta", text: "Tamil" },
//   { value: "tt", text: "Tatar" },
//   { value: "te", text: "Telugu" },
//   { value: "th", text: "Thai" },
//   { value: "ti", text: "Tigrinya" },
//   { value: "ts", text: "Tsonga" },
//   { value: "tr", text: "Turkish" },
//   { value: "tk", text: "Turkmen" },
//   { value: "ak", text: "Twi (Akan)" },
//   { value: "uk", text: "Ukrainian" },
//   { value: "ur", text: "Urdu" },
//   { value: "ug", text: "Uyghur" },
//   { value: "uz", text: "Uzbek" },
//   { value: "vi", text: "Vietnamese" },
//   { value: "cy", text: "Welsh" },
//   { value: "xh", text: "Xhosa" },
//   { value: "yi", text: "Yiddish" },
//   { value: "yo", text: "Yoruba" },
//   { value: "zu", text: "Zulu" },
// ];

const langSelect = document.getElementById("langSelect");

languages.forEach((item) => {
  const optionEle = document.createElement("option");
  optionEle.value = item.value;
  optionEle.text = item.text;
  langSelect.appendChild(optionEle);
});
