const languages = [
  { value: "af", text: "Afrikaans" },
  { value: "sq", text: "Albanian" },
  { value: "am", text: "Amharic" },
  { value: "ar", text: "Arabic" },
  { value: "hy", text: "Armenian" },
  { value: "as", text: "Assamese" },
  { value: "ay", text: "Aymara" },
  { value: "az", text: "Azerbaijani" },
  { value: "bm", text: "Bambara" },
  { value: "eu", text: "Basque" },
  { value: "be", text: "Belarusian" },
  { value: "bn", text: "Bengali" },
  { value: "bho", text: "Bhojpuri" },
  { value: "bs", text: "Bosnian" },
  { value: "bg", text: "Bulgarian" },
  { value: "ca", text: "Catalan" },
  { value: "ceb", text: "Cebuano" },
  { value: "zh-CN", text: "Chinese (Simplified)" },
  { value: "zh-TW", text: "Chinese (Traditional)" },
  { value: "co", text: "Corsican" },
  { value: "hr", text: "Croatian" },
  { value: "cs", text: "Czech" },
  { value: "da", text: "Danish" },
  { value: "dv", text: "Dhivehi" },
  { value: "doi", text: "Dogri" },
  { value: "nl", text: "Dutch" },
  { value: "en", text: "English" },
  { value: "eo", text: "Esperanto" },
  { value: "et", text: "Estonian" },
  { value: "ee", text: "Ewe" },
  { value: "fil", text: "Filipino (Tagalog)" },
  { value: "fi", text: "Finnish" },
  { value: "fr", text: "French" },
  { value: "fy", text: "Frisian" },
  { value: "gl", text: "Galician" },
  { value: "ka", text: "Georgian" },
  { value: "de", text: "German" },
  { value: "el", text: "Greek" },
  { value: "gn", text: "Guarani" },
  { value: "gu", text: "Gujarati" },
  { value: "ht", text: "Haitian Creole" },
  { value: "ha", text: "Hausa" },
  { value: "haw", text: "Hawaiian" },
  { value: "he", text: "Hebrew" },
  { value: "hi", text: "Hindi" },
  { value: "hmn", text: "Hmong" },
  { value: "hu", text: "Hungarian" },
  { value: "is", text: "Icelandic" },
  { value: "ig", text: "Igbo" },
  { value: "ilo", text: "Ilocano" },
  { value: "id", text: "Indonesian" },
  { value: "ga", text: "Irish" },
  { value: "iy", text: "Italian" },
  { value: "ja", text: "Japanese" },
  { value: "jv", text: "Javanese" },
  { value: "kn", text: "Kannada" },
  { value: "kk", text: "Kazakh" },
  { value: "km", text: "Khmer" },
  { value: "rw", text: "Kinyarwanda" },
  { value: "gom", text: "Konkani" },
  { value: "ko", text: "Korean" },
  { value: "kri", text: "Krio" },
  { value: "ku", text: "Kurdish" },
  { value: "ckb", text: "Kurdish (Sorani)" },
  { value: "ky", text: "Kyrgyz" },
  { value: "lo", text: "Lao" },
  { value: "la", text: "Latin" },
  { value: "lv", text: "Latvian" },
  { value: "ln", text: "Lingala" },
  { value: "lt", text: "Lithuanian" },
  { value: "lg", text: "Luganda" },
  { value: "lb", text: "Luxembourgish" },
  { value: "mk", text: "Macedonian" },
  { value: "mai", text: "Maithili" },
  { value: "mg", text: "Malagasy" },
  { value: "ms", text: "Malay" },
  { value: "ml", text: "Malayalam" },
  { value: "mt", text: "Maltese" },
  { value: "mi", text: "Maori" },
  { value: "mr", text: "Marathi" },
  { value: "mni", text: "Meiteilon (Manipuri)" },
  { value: "lus", text: "Mizo" },
  { value: "mn", text: "Mongolian" },
  { value: "my", text: "Myanmar (Burmese)" },
  { value: "ne", text: "Nepali" },
  { value: "no", text: "Norwegian" },
  { value: "ny", text: "Nyanja (Chichewa)" },
  { value: "or", text: "Odia (Oriya)" },
  { value: "om", text: "Oromo" },
  { value: "ps", text: "Pashto" },
  { value: "fa", text: "Persian" },
  { value: "pl", text: "Polish" },
  { value: "pt", text: "Portuguese" },
  { value: "pa", text: "Punjabi" },
  { value: "qu", text: "Quechua" },
  { value: "ro", text: "Romanian" },
  { value: "ru", text: "Russian" },
  { value: "sm", text: "Samoan" },
  { value: "sa", text: "Sanskrit" },
  { value: "gd", text: "Scots Gaelic" },
  { value: "nso", text: "Sepedi" },
  { value: "sr", text: "Serbian" },
  { value: "st", text: "Sesotho" },
  { value: "sn", text: "Shona" },
  { value: "sd", text: "Sindhi" },
  { value: "si", text: "Sinhala (Sinhalese)" },
  { value: "sk", text: "Slovak" },
  { value: "sl", text: "Slovenian" },
  { value: "so", text: "Somali" },
  { value: "es", text: "Spanish" },
  { value: "su", text: "Sundanese" },
  { value: "sw", text: "Swahili" },
  { value: "sv", text: "Swedish" },
  { value: "tl", text: "Tagalog (Filipino)" },
  { value: "tg", text: "Tajik" },
  { value: "ta", text: "Tamil" },
  { value: "tt", text: "Tatar" },
  { value: "te", text: "Telugu" },
  { value: "th", text: "Thai" },
  { value: "ti", text: "Tigrinya" },
  { value: "ts", text: "Tsonga" },
  { value: "tr", text: "Turkish" },
  { value: "tk", text: "Turkmen" },
  { value: "ak", text: "Twi (Akan)" },
  { value: "uk", text: "Ukrainian" },
  { value: "ur", text: "Urdu" },
  { value: "ug", text: "Uyghur" },
  { value: "uz", text: "Uzbek" },
  { value: "vi", text: "Vietnamese" },
  { value: "cy", text: "Welsh" },
  { value: "xh", text: "Xhosa" },
  { value: "yi", text: "Yiddish" },
  { value: "yo", text: "Yoruba" },
  { value: "zu", text: "Zulu" },
];

const langSelect = document.getElementById("langSelect");

languages.forEach((item) => {
  const optionEle = document.createElement("option");
  optionEle.value = item.value;
  optionEle.text = item.text;
  langSelect.appendChild(optionEle);
});
